### ISSUE TITLE
Embedding Kibana elements

### ISSUE THREAD

**Issue by dennlinger** [padieul/yt_scam_scanner#2]
From what I can tell, embedding Kibana elements in other websites should be possible; generally speaking, I would recommend a combination of [dashboard-only mode](https://www.elastic.co/blog/kibana-dashboard-only-mode) with [content embeddings](https://www.elastic.co/guide/en/kibana/current/kibana-authentication.html#embedded-content-authentication).

In the case of singular plots re-created on your UI, you could use an approach similar to the one [detailed here](https://stackoverflow.com/questions/71346909/recreate-kibana-widgets-by-directly-querying-elastic-search-instance), which should allow you to extract elastic queries and combine them with elastic-like plotting.

Let me know if you have any further problems with it and I'll be happy to hop on.

**Comment by padieul** [comment]
Thank you very much! That was very useful!
