### ISSUE TITLE
Types of Spam

### ISSUE THREAD

**Issue by dennlinger** [padieul/yt_scam_scanner#3]
As you mentioned, it seems that no official (informative) paper has been published by Google itself about the spam detection algorithm.
In some pages, I found references to a spam detection bot, but no indication of what particular comments were affected.

The closest indication of what particular comments might be considered spam is listed on the Youtube help site:
https://support.google.com/youtube/answer/2801973?hl=en

This also means that *classifying* the types of spam content might be a meaningful extension of previous works, which are primarily concerned with the detection (from my understanding).

**Comment by vivkaz** [comment]
The latest updates from June 2022 to reduce comment spam and impersonation show that they are still working on the problem:
https://support.google.com/youtube/thread/169359445
However, the information needed is not available. Yes, you are right. One of our goals would be to classify the types of spam comments and the accounts and identify the most common practices.
