### ISSUE TITLE
Best Practice to Store Credentials

### ISSUE THREAD

**Issue by almasria** [padieul/yt_scam_scanner#5]
Hello Dennis,
As you already mentioned in your notes, we have some secrets and credentials stored directly in our code, we would like to know if there  is a best practice to deal with such a case, when we need the credentials to be available inside our code. should we make them input parameters or store them in another gitignored file and use them locally?

**Comment by dennlinger** [comment]
My goto is to `.gitignore` the files that contain secret variables, and then upload a "clean" version with all the "secret variable name" but no actual values.
This usually is then called `secretfilname.extension.template`.

E.g., you could make a `secret.json.template` with the contents

```json
{
   key1 = <INSERT YOUR KEY>,
   secret2 = <INSERT YOUR SECRET>,
   ...
}
```

Of course, this makes it slightly harder to (initially) share the secrets, but will have a lasting effect of being easily understood by outsiders as well.

**Comment by almasria** [comment]
We will work on it, thanks Dennis!
